const options = {
    topType: [
        "NoHair",
        "Eyepatch",
        "Hat",
        "Hijab",
        "Turban",
        "WinterHat1",
        "WinterHat2",
        "WinterHat3",
        "WinterHat4",
        "LongHairBigHair",
        "LongHairBob",
        "LongHairBun",
        "LongHairCurly",
        "LongHairCurvy",
        "LongHairDreads",
        "LongHairFrida",
        "LongHairFro",
        "LongHairFroBand",
        "LongHairNotTooLong",
        "LongHairShavedSides",
        "LongHairMiaWallace",
        "LongHairStraight",
        "LongHairStraight2",
        "LongHairStraightStrand",
        "ShortHairDreads01",
        "ShortHairDreads02",
        "ShortHairFrizzle",
        "ShortHairShaggyMullet",
        "ShortHairShortCurly",
        "ShortHairShortFlat",
        "ShortHairShortRound",
        "ShortHairShortWaved",
        "ShortHairSides",
        "ShortHairTheCaesar",
        "ShortHairTheCaesarSidePart",
    ],
    accessoriesType: [
        "Blank",
        "Kurt",
        "Prescription01",
        "Prescription02",
        "Round",
        "Sunglasses",
        "Wayfarers",
    ],
    hairColor: [
        "Auburn",
        "Black",
        "Blonde",
        "BlondeGolden",
        "Brown",
        "BrownDark",
        "PastelPink",
        "Platinum",
        "Red",
        "SilverGray",
    ],
    facialHairType: [
        "Blank",
        "BeardMedium",
        "BeardLight",
        "BeardMajestic",
        "MoustacheFancy",
        "MoustacheMagnum",
    ],
    clotheType: [
        "BlazerShirt",
        "BlazerSweater",
        "CollarSweater",
        "GraphicShirt",
        "Hoodie",
        "Overall",
        "ShirtCrewNeck",
        "ShirtScoopNeck",
        "ShirtVNeck",
    ],
    clotheColor: [
        "Black",
        "Blue01",
        "Blue02",
        "Blue03",
        "Gray01",
        "Gray02",
        "Heather",
        "PastelBlue",
        "PastelGreen",
        "PastelOrange",
        "PastelRed",
        "PastelYellow",
        "Pink",
        "Red",
        "White",
    ],
    eyeType: [
        "Close",
        "Cry",
        "Default",
        "Dizzy",
        "EyeRoll",
        "Happy",
        "Hearts",
        "Side",
        "Squint",
        "Surprised",
        "Wink",
        "WinkWacky",
    ],
    eyebrowType: [
        "Angry",
        "AngryNatural",
        "Default",
        "DefaultNatural",
        "FlatNatural",
        "RaisedExcited",
        "RaisedExcitedNatural",
        "SadConcerned",
        "SadConcernedNatural",
        "UnibrowNatural",
        "UpDown",
        "UpDownNatural",
    ],
    mouthType: [
        "Concerned",
        "Default",
        "Disbelief",
        "Eating",
        "Grimace",
        "Sad",
        "ScreamOpen",
        "Serious",
        "Smile",
        "Tongue",
        "Twinkle",
        "Vomit",
    ],
    skinColor: [
        "Tanned",
        "Yellow",
        "Pale",
        "Light",
        "Brown",
        "DarkBrown",
        "Black",
    ],
}

const generateAvatar = () => {
    const avatarObj = {
        topType: options.topType[Math.round(Math.random()*options.topType.length)],
        accessoriesType: options.accessoriesType[Math.round(Math.random()*options.accessoriesType.length)],
        hairColor: options.hairColor[Math.round(Math.random()*options.hairColor.length)],
        facialHairType: options.facialHairType[Math.round(Math.random()*options.facialHairType.length)],
        clotheType: options.clotheType[Math.round(Math.random()*options.clotheType.length)],
        clotheColor: options.clotheColor[Math.round(Math.random()*options.clotheColor.length)],
        eyeType: options.eyeType[Math.round(Math.random()*options.eyeType.length)],
        eyebrowType: options.eyebrowType[Math.round(Math.random()*options.eyebrowType.length)],
        mouthType: options.mouthType[Math.round(Math.random()*options.mouthType.length)],
        skinColor: options.skinColor[Math.round(Math.random()*options.skinColor.length)],
    };

    localStorage.setItem("avatar", JSON.stringify(avatarObj));

    return avatarObj;
}

export default generateAvatar;
